const ApplicationTypes = {
    SET_FOLD_DRAWER: 'SET_FOLD_DRAWER',
    SET_FLOATING_HEADER_TOOLS: 'SET_FLOATING_HEADER_TOOLS',
    SET_MEGA_MENU_TOGGLE: 'SET_MEGA_MENU_TOGGLE',
    SET_SETTING_HEADAER_TOGGLE: 'SET_SETTING_HEADAER_TOGGLE'
};

export default ApplicationTypes;