const ApplicationTypes = {
    SET_FOLD_DRAWER: 'SET_FOLD_DRAWER',
    SET_FLOATING_HEADER_TOOLS: 'SET_FLOATING_HEADER_TOOLS',
    SET_MEGA_MENU_TOGGLE: 'SET_MEGA_MENU_TOGGLE',
    SET_SETTING_HEADAER_TOGGLE: 'SET_SETTING_HEADAER_TOGGLE',
    SET_GRID_DASHBOARD_TOGGLE: 'SET_GRID_DASHBOARD_TOGGLE',
    SET_NOTIF_HEADER_TOGGLE: 'SET_NOTIF_HEADER_TOGGLE',
    SET_LANG_HEADER_TOGGLE: 'SET_LANG_HEADER_TOGGLE'
};

export default ApplicationTypes;